AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gif-generator-prakash

  Sample SAM Template for gif-generator-prakash

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Auth:
      Authorizers:
        JWTAuthorizer:
          FunctionArn: !GetAtt JWTAuthorizerFunction.Arn
          Identity:
            Header: Authorization
            VaildationExpression: "^Bearer [-0-9a-zA-Z._]*$"
          PayloadFormatVersion: "2.0"


Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.handler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          GIPHY_API_KEY: cDAxTxW30YYeIBpvlrgf4e9e7KsvZvHK

      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /generator-gif
            Method: get
            Auth:
              Authorizer: JWTAuthorizer
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts


  JWTAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: authorizer.handler
      Runtime: nodejs22.x
      Environment:
        Variables:
          JWT_SECRET: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq3yid5V7wyljFoQVE6dv
            6pHULJvuyWQthEUK1pL+YefpbvnfUXbw5f7uoGX4eHSM/jgwdG8W7H3e/WSXb3SH
            WZmwvIpFUBGOUE5cdkjf8cLXQZCIaykMun6aZlkuBZlaTqyhuPjmAPo8DIgm6cE8
            RayX7Fcq2VMsQ9A7PaXbXkqzbCvea5Q+WWdp6+ShxDhYNQNUWzb1WYl1L1O35eyP
            7OWzYBcOdgMt1JbkBH5dLzC9MLqYx0GAocZU9YdpLXXY0d8fnnZnnlsQ6LRWwhAL
            tRmLqElcdZkG8w5yzJfMBLUXUQNtDpIAXtyowt1K+HhUVtdCwN6w7+GlSRtu5Eeb
            zwIDAQAB
            -----END PUBLIC KEY-----

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - authorizer.ts


    

 
